
site_name: 성경 공부 사이트
theme:
  name: material
  logo: main-image.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: brown
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: blue
  font:
    text: Noto Sans KR
    code: Fira Code
extra_css:
    - stylesheets/extra.css
nav:
  - 홈: index.md
  - 성경 전문 권별: book_of_genesis/Full.md
  - 성경전문세분화:
     - 창세기:
        - 1장~11장: book_of_genesis/fulltext/1to11.md
     - 출애굽기: not_yet.md
     - 레위기: not_yet.md
     - 민수기: not_yet.md
     - 여호수아: not_yet.md
     - 사사기: not_yet.md
     - 룻기: not_yet.md
  - 성경 분석:
     - 창세기:
        - 1장~11장: book_of_genesis/study/all/1to11.md
     - 출애굽기: not_yet.md
     - 레위기: not_yet.md
     - 민수기: not_yet.md
     - 여호수아: not_yet.md
     - 사사기: not_yet.md
     - 룻기: not_yet.md
  - 학습문답식: study_basic.md
  - 그 외 질문들:  not_yet.md